### ISSUE TITLE
Ask for comment when ending or switching tasks

### ISSUE THREAD

**Issue by jesperkdab** [KDAB/Charm#110]
When I stop a task (either by just stopping it, or by switching to another task), it would be useful if charm would ask me what I did during that time, by simply bringing up the edit comment dialog.

As not everyone would like this, it should be an option to enable it.
A further extension to this would be to only do this for certain project code (like the OOC ones). In the simplest case, it could be specified in a lineedit with a coma seperated list of task id's.

**Comment by frankosterfeld** [comment]
Implemented
