### ISSUE TITLE
Ugly appearance with dark theme

### ISSUE THREAD

**Issue by kovtunos** [KDAB/Charm#13]
The application have ugly appearance with dark themes.
What it looks like: http://dl.dropbox.com/u/6763919/blogs/charm-dark.png

p.s. OS: ArchLinux, Charm version 1.5.2
Openbox with dark GTK theme and GTK+ theme of QT in order that apps look similarly.

**Comment by frankosterfeld** [comment]
I assume this is identical with #201 and fixed along with it.
