### ISSUE TITLE
No Charm window on stale config file (Debian-flavoured)

### ISSUE THREAD

**Issue by marc-kdab** [KDAB/Charm#137]
On a fresh install (or under a new user), try:

[0. install the charmtimetracker package]
1. start charmtimetracker, enter your full name, and accept the setup dialog
2. close charmtimetracker
3. apt-get purge charmtimetracker
4. install again
5. start charmtimetracker
-> nothing happens
6. Ctrl-C charmtimetracker
7. rm ~/.config/KDAB/Charm.conf
8. start charmtimetracker
-> initial setup dialog appears

Looks like there's some error checking missing when opening the DB?

**Comment by frankosterfeld** [comment]
Considering it a dupe of #125
