### ISSUE TITLE
Build instructions missing

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#149]
There should be a a BUILD file describing how to build charm, and what the exact requirements are (like Qt features; although making sure cmake checks everything and gives readable errors is preferred wherever possible).

As juan suggests in issue #147:

Actually, it would be enough if a BUILD file existed covering all the compilation specifics. Current README is only about description and project goals, nothing about compilation process, dependencies, etc."

Specifically I'd add that the Qt must have been built with both the D-Bus support and the tools package, which are both optional during the build process but mandatory for Charm compilation.

**Comment by Enigma7995** [comment]
Could someone pick this up?  I am having trouble building the program and some instructions would be very helpful.

**Comment by frankosterfeld** [comment]
@Enigma7995 With a "standard Qt 5 package" as provided by distros or The Qt Company, it should be merely: "Make sure cmake and qmake are in your path" and then cmake .. && make. Which platform are you on and which issues do you see?

**Comment by Enigma7995** [comment]
@frankosterfeld Thank you for the help, I did not have qmake configured correctly.  I am going to get started on improving the application.  I want to make some of the changes I discussed in issue  #203.  Could you give me some feedback?
