### ISSUE TITLE
Font troubles after upgrade

### ISSUE THREAD

**Issue by Blake-R** [KDAB/Charm#155]
Hi. After upgrade to version 1.8.0 (from 1.7.0) I'm have black odd lines in main window and just grey boxes in Tasks Editor widnow. Events Editor persist good.

http://joxi.ru/O4wFU_3JTJCSWTEToIs

**Comment by frankosterfeld** [comment]
Black table rows were fixed with some Qt upgrade (5.4.0? Don't remember exactly). I consider this fixed.
