### ISSUE TITLE
Preference to change password

### ISSUE THREAD

**Issue by winterz** [KDAB/Charm#168]
I changed my password on loc, so then the upload feature failed.  then I realized there was no preference to change the password.

I got around this by choosing "Download Task Definitions" which prompted me for password. then upload feature worked so I assume my password was changed ok.

password changing should be more obvious than that.

**Comment by mgiroday** [comment]
gamaral I am having a look at this issue. It was not implemented yet, right?
/me investigating the source :)

**Comment by mgiroday** [comment]
We have now a reset password option in the preferences dialog.
Fixed with: 44e7128
Status under review

**Comment by mgiroday** [comment]
this one was already merged some times ago. I believe we can close it

**Comment by frankosterfeld** [comment]
Tested, works for me
