### ISSUE TITLE
Linux: Idle detection not ported to Qt 5

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#174]
The idle detection for Linux depends on QX11Info and other X11 headers and hasn't been ported to Qt 5 yet.
(See ifdefs in X11IdleDetector.cpp). It needs investigation whether we should implement it using the X11extras module, or find some other way (xcb?) to implement it.

**Comment by mkae** [comment]
Does the change in title mean that idle detection works on Windows and OSX?

**Comment by frankosterfeld** [comment]
It's flaky and I don't know the status on Windows, but at least there's not Qt5-specific porting problem here.

**Comment by mkae** [comment]
Where is documented how it actually works?

There is only the preference settings 
 * Enable idle detection
 * Enable Bill Lumbergh

but without any further information what these actually mean and/or do.

**Comment by frankosterfeld** [comment]
If Idle detection is enabled, Charm should ask you if you want to continue the current task or stop it at the time you went idle (no keyboard/mouse interaction, suspended laptop) etc. That seems somewhat flaky.

Lumbergh is an internal KDAB option that doesn't make much sense to anyone else (and probably should be hidden better).

**Comment by mkae** [comment]
> If Idle detection is enabled, Charm should ask you if you want to continue the current task or stop it at the time you went idle (no keyboard/mouse interaction, suspended laptop) etc. That seems somewhat flaky.

Hmm, okay, need to check whether I ever see something like that.


> Lumbergh is an internal KDAB option that doesn't make much sense to anyone else (and probably should be hidden better).

I think so. ;-)

**Comment by mgiroday** [comment]
Looking at it

**Comment by mgiroday** [comment]
Implemented an xcb solution for Qt5
Status under review

**Comment by mgiroday** [comment]
was merged
