### ISSUE TITLE
OS X: Black toolbars

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#175]
For some reason, toolbars appear black when using Qt 5 (5.3.2 here) on OS X (10.9 here):

![screen shot 2014-11-03 at 09 16 11](https://cloud.githubusercontent.com/assets/483854/4879829/c46ead2c-6331-11e4-8c75-4127aae7992a.png)

**Comment by pasnox** [comment]
This seems to be a regression since Qt 5.3
