### ISSUE TITLE
Wrong toolbar button states in Tasks editor when no task is selected

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#177]
Charm stores the previously selected task in the tasks editor window and restored that selection on restart. When no selection was made before, no task is selected, but the buttons in the toolbar are enabled where they shouldn't: Edit task, new subtask (also delete task?)  are enabled although no task is selected. They should be disabled in that case instead. 
In debug mode, selecting Edit Task in this situation causes an assertion.

**Comment by cschleifenbaum** [comment]
Fixed here https://codereview.kdab.com/18957
