### ISSUE TITLE
OS X: Search field text only partially visible

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#178]
The text in the search field (reached from Start Other Task) is only partially visible. See screenshot. Might be that Qocoa needs an adaption here for Retina.

![screen shot 2014-11-03 at 12 12 45](https://cloud.githubusercontent.com/assets/483854/4881563/8d5b5632-634a-11e4-83a2-3d8ca71c5e3d.png)

**Comment by pasnox** [comment]
Looks like QMacCocoaContainer regression here too.

**Comment by frankosterfeld** [comment]
Fixed by nuking Qocoa
