### ISSUE TITLE
OS X: Pasting text into search field doesn't trigger filter update

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#179]
Start Other task dialog, search field:

If pasting text via Cmd + V, the filter isn't updated. The tree still shows the old content before the paste.

This seems to affect both Qt 4 and Qt 5. Probably a bug in the Qocoa search field.

**Comment by pasnox** [comment]
Also fixed filter update on cut and select all shortcut on AZERTY keyboards.
