### ISSUE TITLE
OS X: Rendering issue in time tracker view

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#181]
Seen on OS X 10.9, Qt 5.3.2

1) From the dropdown, choose "Start Other Task".
2) The task selector widget opens. 

At the same time, the time tracker gets the white rectangle from the screenshot. This rectangle doesn't go away after closing the task selector or triggering a repaint of the time tracker table.

![screen shot 2014-11-03 at 18 31 21](https://cloud.githubusercontent.com/assets/483854/4886783/6ac904ea-637f-11e4-9bb1-b39b7987081a.png)

**Comment by pasnox** [comment]
The problem clearly comes from QSearchField, replacing it by a QLineEdit works like a .... Charm :p

**Comment by pasnox** [comment]
Looks more like a Qt regression, I do have a workaround fix for that in the main time: forcing application to create native windows/widgets.
