### ISSUE TITLE
Qt4 build doesn't render "Current" and "Selected" buttons correctly in "Task Editor"

### ISSUE THREAD

**Issue by mkae** [KDAB/Charm#187]
On OSX Mavericks these two buttons show on a MacPorts/Qt4 installation only grey circles with a vertical black&white line (first pixel column of texts) instead of the full width of these buttons. Looks like the buttons' sizes aren't getting computed correctly.

Version 1.8.0+ (git hash: aca5faf6)

**Comment by frankosterfeld** [comment]
Could you post a screenshot? Is that a high-resolution (retina) display? We've seen rendering issues with the line edits in the toolbars, not with those buttons though.

**Comment by mkae** [comment]
My Safari doesn't support dropping an image to here. Will thus send it by PM.

**Comment by mkae** [comment]
This is on a 27''-iMac in virtual Parallels 9 machines for Qt4 and Qt5 installed via MacPorts.

The host system runs Qt4 and that's where I see the problem as well.

**Comment by mkae** [comment]
I have noticed that the buttons in question do not behave as the other buttons when changing the settings in "Preferences/Charm Configuration/Buttons show/". They always stay at that "1 row of pixels"-bitmap and never switch to solely or the combination of the two above each other.

**Comment by frankosterfeld** [comment]
Looks like another reason to execute #186

**Comment by mkae** [comment]
yep. Go for it. :+1:

**Comment by mkae** [comment]
This can be closed.
