### ISSUE TITLE
Qt4 version of Charm doesn't start properly after trying to enable "Dictation" on OSX

### ISSUE THREAD

**Issue by mkae** [KDAB/Charm#188]
On my iMac I have a [MacPorts/Qt4](https://trac.macports.org/browser/trunk/dports/aqua/qt4-mac/Portfile) installation with the latest [git version of Charm installed](https://trac.macports.org/browser/trunk/dports/office/charm/Portfile).

Since I tried to enable OSX' Dictation feature Charm is broken.

It doesn't show neither its main menu nor its three windows anymore. It looks as if Charm's ApplicationCore() is not able to load a valid configuration anymore and thus won't construct the main menu etc.

I have no idea how to diagnose this further...

Please give me some hints on how to debug this MVC application!

Alternatively I'd like to know where I can find Charm's configuration file, which I'd love to remove, in the hope that the application starts again from a clean state. Not possible? (I wonder, where the MVC framework saves e.g. stuff like Window sizes and positions...)

**Comment by frankosterfeld** [comment]
Which OS X version is that? Qt4 is quite broken on recent versions of OS X, thus I want the Qt 5 version fixed, and then we'll probably drop Qt4 support for OS X.

**Comment by mkae** [comment]
I am on 10.9.5 running Qt 4.8.6 via MacPorts qt4-mac port.

**Comment by mkae** [comment]
I have found Charm's plist file in ~/Library/Preferences/com.kdab.Charm.plist , but moving it away didn't help, unfortunately. :-( It doesn't get newly created either upon app start.

**Comment by mkae** [comment]
Could it be that OSX needed a reboot after removing that plist file?

Today Charm asked me about my name and then came up with its menu and windows again. :)

**Comment by frankosterfeld** [comment]
From what I know, plist's are cached and it requires one to login again to have them updated.

**Comment by mkae** [comment]
That explains it. Thanks.

**Comment by frankosterfeld** [comment]
As said elsewhere, we're don't support Charm/Qt4 on OS X anymore.
