### ISSUE TITLE
Idle time detection doesn't work on Snow Leopard with Charm's Qt4 version

### ISSUE THREAD

**Issue by mkae** [KDAB/Charm#190]
I have noticed that the idle time detection doesn't work on Snow Leopard (10.6.8) with Charm's Qt4 version.

**Comment by frankosterfeld** [comment]
Does it work for you on newer OS X versions?

**Comment by mkae** [comment]
Yes, it does work on 10.9.5, for instance.

**Comment by frankosterfeld** [comment]
Won't fix, IMHO OS X 10.6 is too old (and out of official Apple support/security updates) for us to care.
