### ISSUE TITLE
Qt4 version creates "Start Dictation..." menu items

### ISSUE THREAD

**Issue by mkae** [KDAB/Charm#191]
The Qt4 version creates "Start Dictation..." menu items on a regular basis in the "Edit" menu.

With time the number of such items increases... Don't know why.

----

The Qt5 version does not show this weird behaviour!

**Comment by frankosterfeld** [comment]
I think that's a Qt 4 issue since OS X 10.8 or so.

**Comment by frankosterfeld** [comment]
Probably won't fix, we'll probably only support Qt 5 on recent OS X versions.

**Comment by frankosterfeld** [comment]
Given that Qt 4 is broken on recent OS X version, we won't spend time on this.
