### ISSUE TITLE
Make it possible to hide invalid tasks in "Search Tasks" dialog

### ISSUE THREAD

**Issue by krf** [KDAB/Charm#192]
(The dialog that pops up when starting new tasks).

Reasoning:
Currently we're getting lots of outdated search results when searching for "training" for instance.

Proposal:
Add this checkbox below the filter line edit:
  [ ] Show invalid entries (default: off)

**Comment by frankosterfeld** [comment]
Wording should be "expired", not "invalid"

**Comment by mgiroday** [comment]
working on it

**Comment by mgiroday** [comment]
Fixed with: bdd0481
Status under review

**Comment by mgiroday** [comment]
merged with 7496c81

**Comment by krf** [comment]
Awesome, thanks!
