### ISSUE TITLE
Clean up last used tasks list

### ISSUE THREAD

**Issue by amantia** [KDAB/Charm#194]
Charm's last used task list from the system tray's context menu shows tasks that are not in use (not Selected) causing visual annoyance. :) As it is not possible to clean it, would be nice if it filters out any revoked or unselected tasks from the list.

**Comment by mgiroday** [comment]
working on this feature

**Comment by mgiroday** [comment]
fixed with a8aed29 - Status: under review ---> https://codereview.kdab.com/#/c/20526/

**Comment by mgiroday** [comment]
merged with: f5fa79d
