### ISSUE TITLE
"Navigation buttons" in weekly and monthly time sheets as well as daily activity reports

### ISSUE THREAD

**Issue by mkae** [KDAB/Charm#197]
I would be nice if the corresponding dialogs would have buttons (like "<" and ">") which allow to navigate to the adjacent day, week, or month.

At the moment one needs to open a new window from the main menu and select the date you aim for resulting in a much longer workflow.

Thus such buttons would be a nice feature.

**Comment by mgiroday** [comment]
working on it

**Comment by mkae** [comment]
Oh, thanks. That would be a really handy thing to have! :+1:

**Comment by mgiroday** [comment]
Fixed with: c0d4f5f
Status under review

**Comment by mgiroday** [comment]
merged with 4375468
