### ISSUE TITLE
Respect "trackable" property from project code XML

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#198]
Complete support for https://quality.kdab.com/browse/LOCA-242

An "isTrackable" (correct name?) property is added to lotsofcake's project code XML. 
We already have a "trackable" task property. Make sure the property is read from the XML and applied to our tasks, and make sure that's it's actually respected in the GUI (i.e. tracking to such tasks is prevented)

**Comment by mgiroday** [comment]
Working on it

**Comment by mgiroday** [comment]
It looks like that is already implemented!
Task::fromXml(const QDomElement& element, int databaseSchemaVersion) is setting the trackable property.
here: 
if ( databaseSchemaVersion > CHARM_DATABASE_VERSION_BEFORE_TRACKABLE ) {
        task.setTrackable(element.attribute(TaskTrackable, QLatin1String("1")).toInt(&ok) == 1);
        if (!ok)
            throw XmlSerializationException( QObject::tr( "Task::fromXml: invalid trackable settings") );
    }

TaskEditor::setTask( const Task& task )
is using this property to set the trackable checkbox value:
m_ui->checkBoxTrackable->setChecked( task.trackable() );

and same for toXML.

anything I am missing here?

**Comment by frankosterfeld** [comment]
The basics works for me: After importing recent project codes with trackable attributes, i cannot choose non-trackable tasks in the task selection tree view. We need to check if starting the task in other ways (if people have them in their time tracker, most used task list, etc.) is also prevented

**Comment by frankosterfeld** [comment]
Choosing a non-trackable task that's already in the time tracker's list or in the recent tasks list (in the combobox) starts tracking without checking for the trackable property.

**Comment by mgiroday** [comment]
fixed. Status under review.

**Comment by mgiroday** [comment]
merged
