### ISSUE TITLE
Clean up Systray menu

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#199]
The systray menu of charm could use some improvements

- There should be a first entry "Open Charm", which should show the time tracker (as many DEs like OS X and Unity now don't allow raising the app by left click)
- Having the show/hide toggle options for the various windows in this menu doesn't make sense, it should just be "Show X".

**Comment by mgiroday** [comment]
Working on it

**Comment by mgiroday** [comment]
Fixed with: 94d5f08
Status under review

**Comment by mgiroday** [comment]
merged with c3532a0
