### ISSUE TITLE
Issues with dark color schemes

### ISSUE THREAD

**Issue by pprkut** [KDAB/Charm#201]
The activity report, weekly and monthly timesheets don't look very usable when presented with a dark color scheme. It looks like the alternating row background is hardcoded to white, yielding light grey text on white background making the whole thing rather difficult to read.

**Comment by milianw** [comment]
Moin Heinz, could you try the above patch - does it also help you? I was nagged by this issue for years but always ignored it. Thanks for bringing it up, this was enough to make me look into it :)

**Comment by frankosterfeld** [comment]
Fixed, thanks Milian!

**Comment by frankosterfeld** [comment]
Didn't wait for pprkut's feedback, but I think this should work for whatever color scheme. So please reopen if not :)
