### ISSUE TITLE
System tray icon missing on Elementary OS

### ISSUE THREAD

**Issue by benediktmag** [KDAB/Charm#202]
I'm running Elementary OS and there is no system tray icon.
When I run Charm I get:
(charmtimetracker:19938): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(charmtimetracker:19938): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(charmtimetracker:19938): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(charmtimetracker:19938): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(charmtimetracker:19938): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
Gtk-Message: Failed to load module "canberra-gtk-module"
No systemtrayicon available

**Comment by benediktmag** [comment]
Solved:
Just needed to install sni-qt.
Maybe is should be added as a dependency?

**Comment by frankosterfeld** [comment]
Never heard of sni-qt. I assume it's a runtime dependency, not compile time?

**Comment by pprkut** [comment]
Yeah, it's a runtime dependency for qt. Elementary OS probably did something similar to what KDE did in Plasma 5, stop supporting the Xembed system tray.
Either way, it wouldn't be a bug in Charm.

**Comment by benediktmag** [comment]
But shouldn't it be added as a runtime dependency?
