### ISSUE TITLE
Incomplete tasks with Qt 5 (Windows)

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#205]
@aholza reports an incomplete task list when import KDAB tasks into the Charm/Qt 5, on Windows.

**Comment by frankosterfeld** [comment]
Scenario: 
- Fresh Charm installation without any tasks
- Download task list XML from lotsofcake
- Import task list

According to @aholza, the tasks in Charm were incomplete (but not empty)

**Comment by mgiroday** [comment]
I cannot reproduce this issue. So on ice for me at the moment

**Comment by frankosterfeld** [comment]
I suspect this was a temporary regression in the master branch when @aholza tested it. Should be retested with a recent package.

**Comment by frankosterfeld** [comment]
Apparently fixed
