### ISSUE TITLE
Charm task selection dialog allows OK with no selection, and then asserts

### ISSUE THREAD

**Issue by dfaure-kdab** [KDAB/Charm#206]
In the Time Tracker window, click on the bottom combo and select "Start Other Task...".
No task is initially selected (as expected), but the OK button is enabled already.
If I click on OK, Charm asserts with 

Charm(23855)/default qt_assert_x: ASSERT failure in void TimeTrackingTaskSelector::populate(const QVector<WeeklySummary>&): "the manually selected task should always be in the menu", file /d/kde/src/charm/charm/Charm/Widgets/TimeTrackingTaskSelector.cpp, line 186

Expected behavior: OK should be disabled until I select a task.

**Comment by mgiroday** [comment]
Could not reproduce. Has probably be fixed with some code under review right now.
Will ping dfaure-kdab when this code is merged for testing again.

**Comment by mgiroday** [comment]
Could finally reproduce working on it

**Comment by mgiroday** [comment]
Fixed - status under review

**Comment by mgiroday** [comment]
merged
