### ISSUE TITLE
Cannot create activity report for non-trackable parent task

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#207]
In the activity report dialog, one cannot select a non-trackable parent task as parent for the activity report, because the task selector doesn't allow to select such a task.
In this case, the dialog should allow for non-trackable (and also expired) tasks, as it's a valid use case to create activity reports for any subtree, no matter whether the task is trackable or not.

**Comment by mgiroday** [comment]
working on it

**Comment by frankosterfeld** [comment]
Same for expired tasks - they should be selectable for reports

**Comment by mgiroday** [comment]
fixed - status under review

**Comment by mgiroday** [comment]
Merged
