### ISSUE TITLE
Add "This Year" to combo box in Activity Report dialog

### ISSUE THREAD

**Issue by krf** [KDAB/Charm#208]
Sometimes this is useful to have, e.g. for tracking remaining vacation days.

**Comment by dfaure-kdab** [comment]
Yes. Also useful when entering vacations for the next 3 weeks, and then wanting to double-check that they got entered correctly, the only way right now is "Ever" which can be a huge list.

**Comment by paltoth** [comment]
Change 23382 - Merged
