### ISSUE TITLE
Systray icons

### ISSUE THREAD

**Issue by sanjasmith** [KDAB/Charm#209]
Since I've installed the Elementary OS 0.3 last time - I've got no icons for Wi-Fi, Skype, any other application that has a tray icon. I only have Language choose, Volume, Bluetooth, Battery and Shut Off button.

**Comment by frankosterfeld** [comment]
If you have icons at all, I'd suspect a Elementary OS issue? If you have other icons but no Charm icon, it might be a Charm (or Qt) issue.

**Comment by sanjasmith** [comment]
I just installed Elementary OS. I didn't do any changes to standard icons.

**Comment by gamaral** [comment]
It looks to me like this is not related to Charm. Maybe ask in the Elementary OS forum or mailing list perhaps?
