### ISSUE TITLE
Task selector does not show non-expired children of expired parents by default

### ISSUE THREAD

**Issue by ahartmetz** [KDAB/Charm#210]
In that kind of situation, the non-expired children are only shown when the option "Show expired entries" is checked. So if you have that situation, the option has only one valid setting which defeats its purpose and shows more clutter.

**Comment by ahartmetz** [comment]
Possibly related to #207

**Comment by frankosterfeld** [comment]
An expired parent with non-expired children sounds semantically broken to me. But Charm should still be able to handle that, I guess.

**Comment by mgiroday** [comment]
looking at this

**Comment by mgiroday** [comment]
fixed - status under review

**Comment by mgiroday** [comment]
merged
