### ISSUE TITLE
Implement update checker

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#211]
Ideally Charm would have a "check for updates" action that checks for updates and actually performs the update. However, the most simple way to get similar functionality would be just to check for updates, tell the user, and let the user download the usual installer by directing him to the download page in his browser. That should be trivial to implement, in comparison.

**Comment by frankosterfeld** [comment]
We'd need to put the update information (a small XML, json file, possibly compressed) on some server, KDAB or github.

**Comment by frankosterfeld** [comment]
The info file would need the following information: for each platform (Windows and OS X): available versions; download link for installer.

The dialog should have a "skip version" and "remind me later" button.

The checker should check on startup and in a certain interval (daily?) and bring up a dialog if a newer than the installed version was found, unless the user blacklisted the update with "skip version". If the user confirms the dialog, it should download the installer (probably via browser, for convenient downloading)

**Comment by mgiroday** [comment]
working on it

**Comment by mgiroday** [comment]
status under review
