### ISSUE TITLE
"No confirmation from server" when uploading empty timesheet

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#213]
1. Create a weekly report for a future (or past) week without any time tracked in it. 
2. Upload that timesheet to lotsofcake, from within Charm

The upload fails and Charm reports "No confirmation from server". 

Assuming that the upload fails due to the timesheet being empty, Charm should give a more useful error message. So either lotsofcake is not reporting the error correctly, or Charm does extract it correctly.

**Comment by mgiroday** [comment]
working on it

**Comment by mgiroday** [comment]
This was fixed with e31fcdfae some times ago.
