### ISSUE TITLE
Search/replace project code in events

### ISSUE THREAD

**Issue by dfaure-kdab** [KDAB/Charm#214]
When someone tells you after 2 weeks "you should have been using project code Y instead of project code X", you have a good 5 minutes of clicking ahead of you, to edit each and every event separately and set the right project code.

This is a feature request for a search/replace dialog, where one could specify a time range, the project code to search, and the project code to replace with.

**Comment by mgiroday** [comment]
Working on it

**Comment by mgiroday** [comment]
under review
