### ISSUE TITLE
Task filter broken

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#215]
As of 1b386de85 (master), the filtering in the task selection dialog doesn't work properly anymore:

I enter a search string (a customer name, ask me directly if you need examples), but the tree shows all kinds of tasks which don't have the string in their name.

**Comment by mgiroday** [comment]
looking at it

**Comment by dfaure-kdab** [comment]
while looking at filtering: I wonder if we could keep subtasks of the filtered one.
E.g. if I type a customer name, I want to be able to choose one of the subtasks even if they are just called "Development", "Testing", etc. Right now it's cumbersome: filter, click on customer name, remove filter, scroll to the selected item again (or a trick, use arrow keys), then finally click on "Development".
Of course I assume this uses QSortFilterProxyModel and therefore this might be non trivial, I can give a hand (proxies are my speciality) if we agree.
AFAICS it's the opposite problem than the one KRecursiveFilterProxyModel solves, but it might be easier (filterAcceptRows returning true if parent matches); plus our data is static, which helps.

**Comment by frankosterfeld** [comment]
@dfaure-kdab That's exactly how it is working now? I am entering a customer name, the whole subtree is  shown.

**Comment by dfaure-kdab** [comment]
OK, ignore my comment, I'm not sure anymore what was the exact problem I was seeing in this regard. Sorry for the noise.

**Comment by mgiroday** [comment]
Status under review
