### ISSUE TITLE
Refactor "Download Definitions"

### ISSUE THREAD

**Issue by milianw** [KDAB/Charm#216]
I'd love to see "Download Definitions" become a thing of the past.

a) first, rename the action to "Update Definitions" or similar
b) please remove the dialogs and use a passive widget to report about the download progress and what changed (if anything). Now, we see three dialogs: 1) download progress. 2) Success that something got imported. 3) What got changed - the last two even require interaction to OK the dialog which is a waste of time.
c) run the update mechanism automatically on startup, or when the user is idle, or when all windows are hidden and no task is running, or ...

**Comment by mgiroday** [comment]
working on it

**Comment by mgiroday** [comment]
Status under review

**Comment by mgiroday** [comment]
was merged
