### ISSUE TITLE
Give better UI hint(s) for non-trackable tasks

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#219]
When selecting a non-trackable parent task in the task selector, the only thing the user notices that the OK button is greyed out. There's no further hint that the task at hand can't be used, and why.
We should add an explanation, either using a label with explanation next to the buttons, or via tooltip.

**Comment by zakalawe** [comment]
Yes, definitely want this. I previously also asked for some feedback when trying to start a recent-but-now-expired task, since previously it would silently fail (with no time being tracked).

**Comment by mgiroday** [comment]
working on it
