### ISSUE TITLE
Task selection tree collapsed when tasks are updated in the background

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#221]
Requires master with the automatic task download.

Steps to reproduce:

- Start charm
- Open the task selector and expand some tasks
- Wait for the task list down in the background to kick in (might have to change timers in charm to delay that) and update the tasks
- The task tree is collapsed once the tasks are updated due to some reset (?) in the model

Expected:

Task list should keep it's expansion and selection state whenever possible (unless the selected task is actually moved or removed)

**Comment by mgiroday** [comment]
Under review

**Comment by frankosterfeld** [comment]
Fixed in ffead82
