### ISSUE TITLE
Monthly report window should be a standalone window

### ISSUE THREAD

**Issue by dfaure-kdab** [KDAB/Charm#224]
I would like to be able to keep the monthly report open, to always see how much time I spent in the month on various projects, compared to the scheduling.

The last column of the monthly report almost does the job, but when I switch virtual desktops and back, the window moves, to be on top of the time tracker window. I would like the monthly report to be a real standalone window like the 3 main windows, so I can keep it open and positioned away from the others.

Ideally, it should also update automatically as time passes, just like the time tracker window does, rather than having to click on Update. In other words I wish for more of a "monthly time tracker" than a report dialog....

But well, if at least it didn't move all by itself, it would be usable ;)
Maybe all that's needed is for it to have no parent window pointer at construction time.

**Comment by mgiroday** [comment]
working on it

**Comment by mgiroday** [comment]
Status under review

**Comment by frankosterfeld** [comment]
The CR slipped through for 1.10.0, scheduling for 1.11.0
