### ISSUE TITLE
Import / Merge Error

### ISSUE THREAD

**Issue by Ogiman71** [KDAB/Charm#226]
During Installation process while "Import & Merge Task..." process starts, system opens an error message (as shown in the screen shot)
![charm](https://cloud.githubusercontent.com/assets/3437217/10044638/dbca54f6-61fc-11e5-9ade-250c598ab8c4.png)

**Comment by frankosterfeld** [comment]
Tested version is  1.10.0RC1

**Comment by frankosterfeld** [comment]
@Ogiman71 Just to avoid any misunderstanding for Michel, can you list the exact steps you did to get there? (run installer, download project code XML...)

**Comment by mgiroday** [comment]
I can't reproduce this after installing from scratch on windows. The task list is imported automatically and I dont get any error message.
"Ogiman71, would be great if you could give me a step by step description about how to reproduce this issue.

**Comment by frankosterfeld** [comment]
I can see this happen when importing a projectcode xml without lotsofcake login information. 
TimeTrackingWindow::importTasksFromDeviceOrFile() calls getUserInfo(), which tries to download the user info without checking if the credentials are available.

**Comment by mgiroday** [comment]
so what do we want to do. Have a better error message adding i.e Check if your credential are up to date or available. Or make a check and instead of calling getUserInfo display a msg and ask the user to register his credentials

**Comment by frankosterfeld** [comment]
@mgiroday "if (!HttpJob::credentialsAvailable())\n return;" or similar in getUserInfo(). 
I still wonder how Daniel can run into this though, assuming his project code xml contains lotsofcake information. We should ensure two things
- if the project code xml doesn't contain credentials, getUserInfo exits (my suggestion above)
- if the project code xml DOES contain credentials, make sure the getUserInfo call actually works

**Comment by mgiroday** [comment]
status under review
