### ISSUE TITLE
Clean up getUserInfo()

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#227]
the getUserInfo code in TimeTrackingWindow has major issues:

* coupling getuserinfo with imported project codes (where getUserInfo is called) is wrong
* It uses a member variable m_user where a temporary would do
* It tries to assign to a const getter (->schema() = m_user) which can't work
* KDAB lotsofcake URL is hardcoded in the code (!)
* slotUserInfoDownloaded() probably fails if someone has less than 10 work hours ("if (weeklyH.length() != 2 )"), does highly fragile json (?) parsing with QString::indexOf and mid, and no error checking at all
* Whitespace is inconsistent and broken

The problem here is to get a decent json parser working with Qt4, I'm not willing to add a qtjson/qt5 dependency just for this feature.

**Comment by mgiroday** [comment]
Where do we want to call getUserInfo from?

**Comment by frankosterfeld** [comment]
@mgiroday 4/ is not related to the tcp server, but to lines like this in TimeTrackingWindow::importTasksFromDeviceOrFile: "settings.setValue( QLatin1String("portalUrl"), QLatin1String("https://lotsofcake.kdab.com:443/KdabHome/apps/portal/"));"
It should use the urls from the project code xml and not hardcode them.

**Comment by frankosterfeld** [comment]
@mgiroday 1/ I'd handle it like automatic downloading of project codes, i.e. start it whenever downloading the project code, reusing the timer for that. Maybe do it before auto-downloading the project code xml. (so that things happen one after another). Also, do it once when the lotsofcake credentials are imported the first time.

**Comment by frankosterfeld** [comment]
Another thing to review is the progress dialog used: I think the userinfo download should be totally "silent" unless there is an error.

**Comment by mgiroday** [comment]
status under review
