### ISSUE TITLE
Charm opens with closed windows when quit from systray

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#229]
Seen by @Ogiman71 on Windows 7: 

When closing all windows and then quitting charm from the systray, the next time Charm starts without showing any window. That's logical, but confusing and not user friendly. It should always show at least the Time tracker window on startup.

Steps:

- Start Charm
- Close the time tracker window
- Close charm from the systray (Quit in context menu)
- Restart charm

Expected:

- Time tracker window becomes visible

Actual: 

- all windows are hidden on startup, Charm is only accessible via the systray icon

**Comment by mgiroday** [comment]
Working on it
