### ISSUE TITLE
Event editor's subscribed tasks filter empty if not all parent tasks are subscribed

### ISSUE THREAD

**Issue by hasselmm** [KDAB/Charm#230]
The event editor has a filter to show only subscribed tasks. Unfortunately it only shows tasks if all its parent tasks also are subscribed. So to see "Project X / 1234 Development", not only "1234 Development" has to be subscribed, but also "Project X", "Customer Y", "Customer projects", ... and so on.

It would be great if the filter would show subscribed tasks even if it's parent tasks are not subscribed yet, or if that's not trivial to implement it would help already if subscribing a task from task editor also would subscribe its parents automatically.

**Comment by mgiroday** [comment]
Working on it

**Comment by mgiroday** [comment]
status under review
