### ISSUE TITLE
Show also events that only end in filter timespan

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#232]
Events that end in the selected event filter timespan but start before it should be also visible.
The filter currently only considers the start date of the event. It should also check for the end date and show the event if /either/ the start date or the end date are in the filter timespan.

Example: Event starts yesterday at 6 pm and ends today at 9 am. 

The event should be visible when the filter is set to either
- "Yesterday" (currently the case)
- "Today" (currently NOT the case)

(And of course this week etc., accordingly)

**Comment by mgiroday** [comment]
Looking at it

**Comment by mgiroday** [comment]
Under review
