### ISSUE TITLE
Filtering in task editor doesn't show child tasks

### ISSUE THREAD

**Issue by dfaure-kdab** [KDAB/Charm#233]
In the "Tasks Editor" window:
if I filter the task list on a customer name, I don't always see the subtasks (which, by themselves, don't match the filter). It just happened again: I type "ibi", I see 0839, but not its subtasks.

They are there, I see them if I remove the filter and scroll down to find 0839 again (cumbersome).

For some reason, this works in the "Select Tasks..." dialog.

**Comment by mgiroday** [comment]
Status: under review
