### ISSUE TITLE
licensecheck 1.9.0

### ISSUE THREAD

**Issue by hefee** [KDAB/Charm#234]
No licenseheader:
* Charm/Keychain/gnomekeyring.cpp
* Charm/Keychain/gnomekeyring_p.h
* Charm/Idle/MacIdleDetector.mm

referece to non existing COPING file; instead of adding this file, switch to the default GPL header like all other files:
* Charm/Keychain/keychain.*
* Charm/Keychain/keychain_mac.cpp
* Charm/Keychain/keychain_p.h
* Charm/Keychain/keychain_unix.cpp
* Charm/Keychain/keychain_unsecure.cpp
* Charm/Keychain/keychain_win.cpp

**Comment by frankosterfeld** [comment]
Thanks, about the keychain files: This code is a copy of https://github.com/frankosterfeld/qtkeychain, and BSD-licensed. So no update wanted/necessary. The headers should be added to gnomekeyring_p.h/cpp though, and the Charm copyright header should be added to MacIdleDetector.mm.

**Comment by winterz** [comment]
I'll take this

**Comment by winterz** [comment]
fixed in the 1.10 and master branches
