### ISSUE TITLE
textual representation of events too cryptic

### ISSUE THREAD

**Issue by Ogiman71** [KDAB/Charm#235]
When a user want to delete a message he/she gets a message as expected.
But the end of the message is a bit cryptic, because it shows only the start time, but not the end time, in the middle (as shown in the attached screen shot). 
![cryptic_message](https://cloud.githubusercontent.com/assets/3437217/10307333/580d6158-6c2e-11e5-9371-ac0cc355dfac.png)

**Comment by mgiroday** [comment]
Looking at it

**Comment by mgiroday** [comment]
Status under review
