### ISSUE TITLE
patches on debian

### ISSUE THREAD

**Issue by hefee** [KDAB/Charm#241]
Fotr the debian pakage I added two patches to have "better" packages for debian. I'm not sure if they are also interesting for you.

* Use QtKeychain from the system itself and don't use the copy: [use_system_qtkeychain.patch](https://anonscm.debian.org/cgit/pkg-kde/kde-extras/charmtimetracker.git/tree/debian/patches/use_system_qtkeychain.patch)
* Not install license and readme in doc dir, because debian does this own its own [notinstall_license.txt.patch](https://anonscm.debian.org/cgit/pkg-kde/kde-extras/charmtimetracker.git/tree/debian/patches/notinstall_license.txt.patch)

If there is iterest in the patches, i can polish them and make a pull request.

**Comment by frankosterfeld** [comment]
Hmm, I could imagine a patch that uses the system-provided qtkeychain if available in the required version, and using the local copy otherwise.

Don't know about the requirements for license file installation on other distros. If that's Debian-specific, it's probably better kept as patch, otherwise it could go upstream. @winterz Do you happen to know anything about this?

**Comment by winterz** [comment]
qtkeychain does seem pretty widespread by now.  but I think using the copy if find_package(Qt5Keychain REQUIRED) fails is a good compromise.

as for the license files. and a policy for that.  I don't know how widespread such a policy is. so I'd like to not change the CMakeLists.txt file but I'm not against some sort of exclusion for debian.. but how does one check for debian in a CMakeLists.txt file? http://stackoverflow.com/questions/23491890/how-to-differentiate-ubuntu-and-debian-in-cmake

hefee will you make such and create the pull requests?

**Comment by hefee** [comment]
If you don't want to change the installation of license behaviour completly than I think a local patch is the best way to go. Because there is no clean way to detect that we are building a debian package. And the debian package is consumed by ubuntu, mint, tanglu, ... so we would need to add all child distros, if we would go the etc/issue way. Or we use env in debian/rules to modify the installation. All in all it looks for me that the best solution so far is to handle this in a debian patch.

because I have already created a patch for /etc/issue:

```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -259,7 +259,24 @@ CONFIGURE_FILE( CharmCMake.h.cmake ${CMAKE_CURRENT_BINARY_DIR}/CharmCMake.h )
 
 SET( LICENSE_FILE "License.txt" )
 SET( README_FILE "ReadMe.txt" )
-IF( NOT APPLE )
+
+SET( DEBIAN FALSE )
+SET( UBUNTU FALSE )
+
+FIND_FILE(ISSUE "issue" "/etc")
+IF (NOT ISSUE STREQUAL "ISSUE-NOTFOUND" )
+       FILE(READ "${ISSUE}" ETC_ISSUE)
+       STRING(REGEX MATCH "Debian|Ubuntu" DIST ${ETC_ISSUE})
+       IF(DIST STREQUAL "Debian")
+           MESSAGE( STATUS ">>>> Found Debian <<<<" )
+           SET( DEBIAN TRUE )
+       ELSEIF(DIST STREQUAL "Ubuntu")
+           MESSAGE( STATUS ">>>> Found Ubuntu <<<<" )
+           SET( UBUNTU TRUE )
+       ENDIF()
+ENDIF()
+
+IF( NOT APPLE AND NOT DEBIAN AND NOT UBUNTU )
     INSTALL( FILES "${LICENSE_FILE}" "${README_FILE}" DESTINATION ${DOC_INSTALL_DIR} )
 ENDIF()```
