### ISSUE TITLE
Remove notification about updated tasks

### ISSUE THREAD

**Issue by tmcguire** [KDAB/Charm#245]
From time to time, I see a notification popup in the system tray about updated tasks.
I find this notification distracting, especially when presenting something in non-fullscreen mode.

Please remove the notification popup, or provide an option to disable it.

**Comment by frankosterfeld** [comment]
We could remove any notification unless an error occurs which isn't a connection error (assuming that those are either caused by lotsofcake being down or the network connectivity not working).

**Comment by tmcguire** [comment]
That would be a good solution.

**Comment by winterz** [comment]
Also, can the notification pop-up texts somehow indicate that they come from Charm?
i.e. "Charm Tasks Successfully Updated" is better than "Tasks Successfully Updated"

**Comment by frankosterfeld** [comment]
@winterz Need to check the platforms, I think at least on OS X the application title is included in the popup, which would make it slightly redundant.

**Comment by hasselmm** [comment]
Also might work to use obviously charm specific icons besides the notification text, but no idea if that's portable.

**Comment by frankosterfeld** [comment]
For those who see deficits, please state which desktop you're using. Bonus points for screenshots of how it looks now. (and yes, this should be a new issue).

**Comment by frankosterfeld** [comment]
See also #257

**Comment by frankosterfeld** [comment]
Fixed in 5976b53
