### ISSUE TITLE
The systray icon context menu ( right click on it ) shows both the custom Quit action and the kde kf5 quit button - KDE Plasma 5

### ISSUE THREAD

**Issue by mgiroday** [KDAB/Charm#248]

**Comment by mgiroday** [comment]
kf5 version

michel@tamatave:~/kf5-config --version
Qt: 5.4.2
KDE Frameworks: 5.15.0
kf5-config: 1.0

C
![quit](https://cloud.githubusercontent.com/assets/12032167/11396845/0317fcbc-9375-11e5-8e24-b66fcc6dab3e.png)
harm compiled against qt 5.5

**Comment by mgiroday** [comment]
I cant reproduce this anymore. Same kf5 config as above and compiling Charm against Qt 5.5.1

**Comment by frankosterfeld** [comment]
Seems fixed with recent KDE/KF5 versions, I only have our own button (the upper one in the screenshot) there now.
