### ISSUE TITLE
Use Windows taskbar extension features

### ISSUE THREAD

**Issue by AndreSomers** [KDAB/Charm#249]
When running Charm on Windows, it would be nice to use the taskbar extension features to offer some quick access to features:

* A start/stop button and quick task switch (2/3 most recent tasks?) using the Thumbnail Toolbar. Should also indicate the currently running task clearly if a task is currently active.
* A bigger list of recent tasks to start using the Jump list.

This would make it easier to use Charm without having to actually bring the window to the front.

**Comment by frankosterfeld** [comment]
Note to team: See https://msdn.microsoft.com/en-us/library/windows/desktop/dd378460(v=vs.85).aspx

**Comment by AndreSomers** [comment]
Well, Qt has direct support for it on Windows: http://doc.qt.io/qt-5/qtwinextras-overview.html
