### ISSUE TITLE
Running in KDE KF5 (Arch Linux)

### ISSUE THREAD

**Issue by tuxflo** [KDAB/Charm#253]
Hey there!
I was looking for a new timetracker since ktimetracker is not working with kde-kf5 anymore.
I did:

     git clone && cd charm
     mkdir build && cd build
     cmake ..
and everything just compiled fine. But when I try to start the application using `./charmtimetracker` Nothing happens. Neither output on the commandline, nor any window or tray icon opens.
Any ideas how to start debugging? Do debugging flags like `--debug` exist?
I'm using Arch Linux (manjaro) with KDE plasma as Desktop Environment.
![selection_011](https://cloud.githubusercontent.com/assets/2816893/11993815/ac046a78-aa35-11e5-816f-cd23f5a4445d.png)

**Comment by krf** [comment]
This works fine for me.

Note: You may need to install a support package to get the Charm tray icon.

On Ubuntu, this package is called `sni-qt`
