### ISSUE TITLE
Search & Replace a removed project code

### ISSUE THREAD

**Issue by Knarf64** [KDAB/Charm#255]
Hi, 

Here the situation : 
you spend 3 days on project code, and it was wrong, the new one is here, and the old one has been removed to avoid any further confusion since it was obsolete. Well, in the search and replace menu you can only choose within available project code. 

Would be awesome to be able to choose from old code ( or selecting in the list of tasks ( with a filter line edit) ) and then replace with the new one. 

No sure I'm really clear, ask if not :)
Cheers

**Comment by dfaure-kdab** [comment]
In the Find and Replace dialog, when you click on "Find: [Select Task]", the dialog that pops up has two checkboxes: Show expired, Show only subscribed.
If you check the first one, and uncheck the second one, you can choose an obsolete project code.
So I think what you're asking for, is already implemented.

**Comment by krf** [comment]
I just ran into this.

You can select an obsolete project code, but you can't click "OK" on the dialog. => Not possible to do a search-replace on an obsolete project code.

**Comment by krf** [comment]
```
diff --git a/Charm/Widgets/SelectTaskDialog.cpp b/Charm/Widgets/SelectTaskDialog.cpp
index adac88c..6517d3b 100644
--- a/Charm/Widgets/SelectTaskDialog.cpp
+++ b/Charm/Widgets/SelectTaskDialog.cpp
@@ -155,6 +155,7 @@ void SelectTaskDialog::slotCurrentItemChanged( const QModelIndex& first,
         m_ui->taskStatusLB->clear();
     } else {
         m_selectedTask = 0;
+        // ^ bad boy
         const bool expired = !task.isCurrentlyValid();
         const bool trackable = task.trackable();
         const bool notTrackableAndExpired = ( !trackable && expired );
```

Line above comment is the issue. The task selector dialog should allow selecting obsolete tasks for certain use-cases (i.e. in the search-replace context)
