### ISSUE TITLE
Cannot create task

### ISSUE THREAD

**Issue by greenrd** [KDAB/Charm#256]
I installed in Fedora 23 using the Fedora 22 RPM for x86_64. When I pressed T to create a task, I could enter the task name but clicking in the unnamed textarea did nothing, and the OK button was disabled.

**Comment by greenrd** [comment]
I also tried to create a task by pressing Ctrl+N in the task editor window, but the created task did not appear.

**Comment by frankosterfeld** [comment]
Could you please add a screenshot? "clicking in the unnamed textarea did nothing" does that mean that the text edit cannot be focused and you can't enter text?

**Comment by greenrd** [comment]
Yes, exactly.

But I did figure out how to do it just now - I created a task using Ctrl+N (as I said in my previous comment) and now with the T key I can start that task. It seems I misunderstood how to use the program. The "unnamed textarea" was not a task description, as I had assumed - it was a list of tasks.
