### ISSUE TITLE
Only try to update task list when connected to the internet

### ISSUE THREAD

**Issue by milianw** [KDAB/Charm#257]
When I boot up my laptop, I'm usually greeted first with the error message from charm that the task list could not be updated. The reason is that it tries to update that right after start. My laptop usually needs ~1min or so to connect to wireless.

I propose this situation is improved by detecting whether an internet connection is available (solid?) and then update the task list based on that information.

**Comment by frankosterfeld** [comment]
Either detect or just silently fail in certain cases (like host not found etc.)

**Comment by frankosterfeld** [comment]
Now that commit gets the error code through the httpjob wrapper, but doesn't change anything yet about showing the popup.
