### ISSUE TITLE
Replace three main windows with single main window

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#261]
The "three mainwindow" approach in Charm must die.

* Time Tracker should be the only main window
* Tasks and event editors should be non-modal dialogs one can open from the menu/via shortcut
* The Time Tracker should always be visible (no "tasks editor visible, others hidden")

**Comment by hasselmm** [comment]
+100

**Comment by dfaure-kdab** [comment]
"Hide Time Tracker Window" is still a menu item. Wasn't this change at least supposed to get rid of that?
