### ISSUE TITLE
No error details on lotsofcake upload failure

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#262]
I've got reports that when uploading a timesheet with expired project codes to current lotsofcake (1.21.0), people get "An error occurred, could not extract details" as error message. That means something goes wrong when extracting the error message from the XHTML.

**Comment by frankosterfeld** [comment]
The issue is a "&rArr;" in the XHTML, which is unknown to QXmlStreamReader and lets it throw an error.

**Comment by frankosterfeld** [comment]
Eh, linked wrong bug in commit msg

**Comment by mkae** [comment]
A question: What is actually "lotsofcake"? Is that a KDAB internal database?

If so, could Charm also be used with some central database for non-KDAB people?

**Comment by frankosterfeld** [comment]
Yes, "lotsofcake" is KDAB's internal server managing the task list and processing uploaded weekly timesheets from KDAB's employees, among other things. One could implement something like that to work with Charm, it would have generate a task list in the XML format that can be imported via "Import and Merge Task Definitions" and be able to import the weekly timesheet XML. That's how Charm and lotsofcake interacted for a long time. Now there's lotsofcake integration in Charm for more convenience task list updating and timesheet uploading, but that's not necessary to get started. If there's serious interest, one could consider "standardizing" a basic REST API for charm to talk against, although I can't promise that it would happen. Another option would be to factor out the lotsofcake integration into a plugin and allow other plugins for other server backends.

**Comment by frankosterfeld** [comment]
What I described was assuming that you're asking for a backend companies could use, if you're thinking about a database for a single person, to use charm on multiple computers, then that's issue #251 without having a solution yet.

**Comment by mkae** [comment]
Thanks for the info. I am thinking about a small team synching against some central database on one hand, but the single user case is also interesting.

**Comment by frankosterfeld** [comment]
Worked around by changing the XHTML in lotsofcake to not use & rarr;, proper fix would be to use the REST API.
