### ISSUE TITLE
Allow event currently running to edit its comment property

### ISSUE THREAD

**Issue by pasnox** [KDAB/Charm#263]
Actually, editing a running event only allow to change its start date.
I would appreciate to be able to change its comment to.
I often want to change the comment while running to set the currently related work task id inside.
Until now i'm forced to stop and start a new event - quite boring.

**Comment by dfaure-kdab** [comment]
This is already available, using the pen-on-paper (edit) icon in the *Time Tracker* window.

**Comment by pasnox** [comment]
Ho indeed, thanks!!
So it's a total non sense to not be able to edit it from the Events Editor window :)
So this is still a valid issue / enhancement, but with low priority.

**Comment by frankosterfeld** [comment]
Fix up for review in KDAB gerrit
