### ISSUE TITLE
Ampersands get duplicated when task is active

### ISSUE THREAD

**Issue by cwickert** [KDAB/Charm#265]
When you have a task name with an ampersand, say _"Communication & Coordination"_ it looks fine in everywhere but in the task selector. It's ok in the dropdown, but once it is selected, the ampersand gets duplicated and the names becomes _"Communication && Coordination"_.

![screenshot_2016-03-10_09-29-46](https://cloud.githubusercontent.com/assets/972070/13663681/2e4d0d7e-e6a3-11e5-84dc-130edb8c6240.png)

**Comment by cwickert** [comment]
Forgot to mention: This is charm 1.1.10 on OpenSUSE Leap 42.1 from [OBS.](https://build.opensuse.org/project/show/isv:KDAB)

**Comment by frankosterfeld** [comment]
@cwickert: Which Qt version is that?

**Comment by cwickert** [comment]
4.8.6 from SUSE's libqt4-4.8.6-5.2.x86_64 package(s).

2016-03-10 10:49 GMT+01:00 Frank Osterfeld <notifications@github.com>:

**Comment by frankosterfeld** [comment]
Reproducible also with Charm master, Qt 5.6:

1. Start Charm in a clean install, without any tasks
2. In the task editor, create a task "A & B"
3. In time tracker, select that task in the menu, via "start other task". First it appears as "A & B"
4. Then select it again from the menu. => The text is now replaced by "A && B"

**Comment by frankosterfeld** [comment]
Fix up for review in KDAB gerrit
