### ISSUE TITLE
Charm doesn't restore the size and position of the tasks editor and event editor anymore

### ISSUE THREAD

**Issue by dfaure-kdab** [KDAB/Charm#267]
2cc2d87eb7720e made things worse IMHO.

When I start Charm, I no longer get the tasks editor and event editor visible, even if they were visible on closing. Worse, showing these windows uses awful default sizes. The tasks editor (Tasks View, says the caption, inconsistent with the menu item) and the event editor both show up very very tiny, no matter what size I gave them last time.

When I saw requests about a single mainwindow, I thought this meant we'd have a proper GUI with everything needed in it, not that it would like before but worse because we have to reopen and resize the useful windows by hand every time.

Short term I propose to revert 2cc2d87eb7720e.
Medium term I propose to think about a proper single-window GUI which would offer all of the needed functionality -- e.g. using splitters or tabs or dockwidgets.

**Comment by dfaure-kdab** [comment]
"Show <foo> Window" should also raise the window. Right now it stays below other windows (from Charm or from other processes).

**Comment by TheOneRing** [comment]
I agree that "Show Windows" should raise the window also the windows should be restored properly.

**Comment by frankosterfeld** [comment]
For events, merging them with the time tracker would make sense to me (Bjoern's mockup he showed me once has that, iirc). The task editor on the other hand is so rarely used that i think that an extra dialog should be fine. I think we shouldn't restore window visibility but restore size/position.

**Comment by TheOneRing** [comment]
Fixed in https://github.com/KDAB/Charm/commit/4da6a6bafb0d2cba04dcd4609d4717241dbdab98
