### ISSUE TITLE
Windows jump list is filled with old tasks

### ISSUE THREAD

**Issue by AndreSomers** [KDAB/Charm#272]
The newly implemented windows jump list seems quite useless. It is filled with old tasks. Both the recent and the frequent list contain the same entries. The contents of these are neiher frequently used or recently used. Instead, these seem to be tasks from when I first started using Charm. 

There is already another list of recent tasks, connected to the task tray icon. That list _does_ make sense. Perhaps the lists should be connected?

**Comment by TheOneRing** [comment]
Hi are you using 0.11.0 or 0.11.1?
The jump list's are controlled by charm only, the problem is that a clear() on the jump list object doesn't remove the entries from the previous run...

**Comment by AndreSomers** [comment]
I am on 1.11.0

André

Op 04/05/2016 om 09:20 schreef Hannah von Reth:

**Comment by TheOneRing** [comment]
Can you try 1.11.1, the new version should reduce the lag on task change, and the new version only sets the recent category with the most recent items.

**Comment by TheOneRing** [comment]
Is this still an issue?

**Comment by AndreSomers** [comment]
No, works like a Charm now.
