### ISSUE TITLE
When charm is started from the installer it runs in the admin space.

### ISSUE THREAD

**Issue by TheOneRing** [KDAB/Charm#276]
When charm is started from the installer it runs in the admin space. This breaks the single instance code.

**Comment by frankosterfeld** [comment]
Maybe we can get rid of the option to start charm from the installer?

**Comment by TheOneRing** [comment]
That's what I was thinking too.

**Comment by TheOneRing** [comment]
Hm all I can find for cpack is https://cmake.org/Wiki/CMake:CPackConfiguration  and nothing about running an application on exit. 
The closest thing would be 
`CPACK_PACKAGE_EXECUTABLES  List of pairs of executables and labels. Used by the NSIS generator to create Start Menu shortcuts.  `
