### ISSUE TITLE
Specify License for FindXCB.cmake more precisely

### ISSUE THREAD

**Issue by hefee** [KDAB/Charm#278]
Charm/CMake/Modules/FindXCB.cmake:
"Redistribution and use is allowed according to the terms of the BSD license"

-> is this now BSD 2 or 3 clause? A full license header must be added, if this is distributed with a different license than the rest of the project. It is the only file that is licensed under BSD. Maybe you could relicense it under GPL2+. According to blame @winterz and @mgiroday are the authors of this file.

**Comment by winterz** [comment]
hi hefee.  I can handle this one.  we're fine relicensing to GPLv2+.

**Comment by winterz** [comment]
fixed in commit cc6ce0f1c640e7fb04f098586bdf11a08ade86b6
