### ISSUE TITLE
Replace task cannot be selected in Search/Replace dialog

### ISSUE THREAD

**Issue by AndreSomers** [KDAB/Charm#281]
When trying to update a project code, I was attempting to use the search & replace option. Unfortunately, the button to open the task selector for the replace task does not work, thus rendering the dialog useless. 

OS: Linux, version 1.11.1

**Comment by frankosterfeld** [comment]
What do you mean with "does not work"? It works for me here, one first needs to select the "Find" task, then the "Replace with" task (the order restriction seems unnecessary though)

**Comment by AndreSomers** [comment]
I mean: does not work. No dialog opens for me when I click that button, while for the Find - Select Task button I do get the Select Task... dialog, nothing happens if I click the Replace With - Select Task button.

**Comment by frankosterfeld** [comment]
So the replace with button stays disabled even after you selected a task for "Find"?

**Comment by AndreSomers** [comment]
No, it is enabled. It just doesn't _do_ anything.

**Comment by TheOneRing** [comment]
Could you provide a concrete example with all steps, as I fail to reproduce that behaviour.

**Comment by AndreSomers** [comment]
I cannot reproduce it anymore either. It may have been that I am confused by my widget style, which does not show the style to be disabled very clearly. I only see a difference in behavior when I hover over it, so earlier the button may have looked enabled to me but it really wasn't. So, I think that perhaps I did not have a find selected yet, but I am not sure any more.

What is the reason that the enabled status of the replace button depends on having a find task selected already? Why force the order?

**Comment by frankosterfeld** [comment]
I agree, enforcing the order seems unnecessary
