### ISSUE TITLE
Expand task tree when searching

### ISSUE THREAD

**Issue by milianw** [KDAB/Charm#282]
To reproduce:

* Edit -> Start Other Task
* select e.g. task 2068 and accept
* Go again to Edit -> Start Other task
* Search for something in another branch of the task tree, e.g. now 9998

Actual behavior:

    0001
      |- 9990

i.e.  9990 is unexpanded with the searched-for 9998 one level below and one needs to manually expand the item.

Expected behavior:

    0001
      |- 9990
        |- 9998

Bonus points if 9998 (the only match) would be selected directly so that I can accept the dialog quickly by pressing enter.

**Comment by TheOneRing** [comment]
Hm actually it should already be expanded?
https://github.com/KDAB/Charm/blob/master/Charm/Widgets/SelectTaskDialog.cpp#L202
https://github.com/KDAB/Charm/commit/9a3637c0ee23cbb6072aa8045676016e0cb3dd11

**Comment by milianw** [comment]
indeed, seems to be implemented now! thanks
