### ISSUE TITLE
Allow to directly resume after idle detection

### ISSUE THREAD

**Issue by dschmidt** [KDAB/Charm#291]
Right now Charm only allows to stop tracking when idle state was detected and to completely end tracking or to ignore idle time. I would like to click "yes, i was idle, please continue tracking from now"

**Comment by petr-fischer** [comment]
+1 

And question: how is idle state detected? (I have some problems with idle detection on FreeBSD and need detect/debug more, thanks)

**Comment by dschmidt** [comment]
:heart:
