### ISSUE TITLE
No default destination during installation process 

### ISSUE THREAD

**Issue by Ogiman71** [KDAB/Charm#295]
Version: 1.11.1
During the installation process the user should chose the folder where charm should be installed, but the textfield of the destination folder is empty atm
![no_default_destination](https://cloud.githubusercontent.com/assets/3437217/19436995/98651a16-9473-11e6-82bf-e13f8c41e026.png)

**Comment by frankosterfeld** [comment]
@TheOneRing This is current master, i.e. after your rewrite of the installer, can you have a look please?
