### ISSUE TITLE
Usability: Activity Report configuration dialog too big and too complex

### ISSUE THREAD

**Issue by frankosterfeld** [KDAB/Charm#302]
The activity report configuration dialog became an unusable monster:

<img width="516" alt="screen shot 2016-10-31 at 10 08 53" src="https://cloud.githubusercontent.com/assets/483854/19849331/ebdb4460-9f52-11e6-81fc-9241c5c0c030.png">

On my Macbook 13" it takes full screen height when expanding the advanced section.
It should be more compact and take tons of space for options (include/exclude) not used most of the time.

**Comment by mkae** [comment]
I am afraid this is due to Qt5's excessive spacing these days... Saw this happening also with so many Qt-based KF5 apps on KDE.

**Comment by frankosterfeld** [comment]
The UI design seems broken to me besides any spacing issues...
