### ISSUE TITLE
behave correctly with suspend/resume

### ISSUE THREAD

**Issue by petr-fischer** [KDAB/Charm#309]
When I suspend laptop with charm running, when resume, nothing useful happens.
Some reaction like idle detection is needed (you can detect it by long actual system time jumps, maybe...).

**Comment by frankosterfeld** [comment]
Which platform are you on?

**Comment by petr-fischer** [comment]
FreeBSD 11.0-RELEASE amd64, standard Xorg, i3 window manager.

**Comment by petr-fischer** [comment]
Just retested latest FreeBSD build and can't reproduce this issue. Closing...
