### ISSUE TITLE
idle detection dialog doubled

### ISSUE THREAD

**Issue by petr-fischer** [KDAB/Charm#311]
Now, in 1.11:

1) when idle time is detected, idle detection dialog appears
2) then I select proper answer, click OK
3) then, idle detection dialog (second) appears immediately again (+ main window glimmer once)

Platform: FreeBSD

**Comment by petr-fischer** [comment]
Just retested latest FreeBSD build and can't reproduce this issue. Closing...

**Comment by paltoth** [comment]
I can reproduce it, just have to wait more then two times of the idle period (>2*3min)

**Comment by paltoth** [comment]
Resolved.
