### ISSUE TITLE
"Enable idle detection" greyed out in 1.12.0

### ISSUE THREAD

**Issue by hackel** [KDAB/Charm#333]
I installed 1.12.0 from the OpenSuse build service on Ubuntu 18.04, and now idle detection is disabled.  It works fine with 1.11.4-2 that is in Ubuntu.  I have both libxcb1 and libxcb-screensaver0 installed, which are listed in the Ubuntu package's dependencies, but not the OpenSuse package.  I suspect this is because Build-Depends in the dsc file is missing libxcb1-dev and libxcb-screensaver0-dev.  I recompiled it using the same dsc and control files provided by the Ubuntu (Debian) package and it seems to have worked fine.

**Comment by winterz** [comment]
@hackel indeed. I will fix today

**Comment by winterz** [comment]
fixed in 5c955a61444bb02d7f7251c1cc1c2e002d5c9660, I hope.

A some point the OBS will give you updated packages
