### ISSUE TITLE
Question: How to create a new task?

### ISSUE THREAD

**Issue by diversemix** [KDAB/Charm#345]
How do you create a new task?
Things I have tried ... 

- Double clicking in the empty task view.
- Menu option: "Start Other Task..."
- Menu option: "Preferences" .. cannot find anything here
- Reading the README.md ... found the sentence `They have to be created manually` - However, no instructions on how to achieve this.
- Looked for outstanding issues - found #256 however Ctrl+N does not work for me :cry:

**Comment by frankosterfeld** [comment]
There's a separate editor window for it, Window->Show Tasks Editor window in the menu.
