### ISSUE TITLE
Building on Windows Error (MinGW, 32bit)

### ISSUE THREAD

**Issue by katrinaniolet** [KDAB/Charm#85]
[ 80%] Building CXX object Charm/CMakeFiles/CharmApplication.dir/keychain_win.cp
p.obj
C:\Users\katrina\workspace\charm\Charm\keychain_win.cpp: In member function 'QKe
ychain::Keychain::Error QKeychain::Keychain::Private::readEntryImpl(QByteArray*,
 const QString&, QString*)':
C:\Users\katrina\workspace\charm\Charm\keychain_win.cpp:49: error: 'SecureZeroMe
mory' was not declared in this scope
mingw32-make[2]: *** [Charm/CMakeFiles/CharmApplication.dir/keychain_win.cpp.obj
] Error 1
mingw32-make[1]: *** [Charm/CMakeFiles/CharmApplication.dir/all] Error 2
mingw32-make: *** [all] Error 2

Using CMake 2.8.8, Qt 4.8.1, MinGW 4.4 (the last two being installed from the Qt SDK) and OpenSSL 1.0.1c

**Comment by frankosterfeld** [comment]
Closing, can be reopened if someone has the urgent need to build Charm with mingw and can provide current build errors.
